# Generated by Django 5.0.6 on 2024-06-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='race',
            field=models.IntegerField(choices=[(1, 'Cat'), (2, 'Dog'), (3, 'Bird')], default=1),
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=1),
        ),
    ]
