# Generated by Django 5.0.6 on 2024-06-16 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=50)),
                ('scientific_name', models.CharField(max_length=50)),
                ('is_exotic', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('affected_animal', models.ManyToManyField(to='base.race')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('is_for_special_needs', models.BooleanField(default=False)),
                ('ingredients', models.TextField(blank=True)),
                ('adequate_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.race')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('affected_animal', models.ManyToManyField(to='base.race')),
            ],
        ),
    ]
